# Generated by Django 3.2.16 on 2023-02-12 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='/Product-Image-Coming-Soon.jpg', null=True, upload_to=''),
        ),
    ]
