# Generated by Django 3.2.16 on 2023-02-17 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        ('orders', '0002_rename_orders_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cartitems',
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(to='product.Product'),
        ),
    ]
